### ISSUE TITLE
Battery problem

### ISSUE THREAD

**Issue by truefriend-cz** [zeelog/OTA#1]
Hello. Battery level issue. Every approx. 30 seconds, it turns off for about half a second and turns on the LED while charging the battery.

Edit:
This úproblem have both versions Kernel 3.8 and 4.9.230, 4.9.231.

**Comment by africabloe** [comment]
Hello my friend. I am on a mido group with 3 people on Telegram. All of us have flashed on our Redmi Note 4X Zeelog's LineageOS 17.1 Q (3.18 & 4.9). All the versions that you mention on your comment, are working much better than expected. Every update the operation of the mobile is getting better and better. The last one update of the 4.9 release with the stock kernel, is working so good that we have not even the need to use MoeSyndrome kernel or the CAF kernel. We are not have this kind of problem that you mention. Something you did during the flash of the rom maybe caused these problems on your battery...

**Comment by truefriend-cz** [comment]
Well, with such an approach, I'm not surprised that not only this works. Could you have a slightly smaller ego and a little better approach to the problem professionally? Rather than praising your ROM, I would welcome a way to, for example, record a thing and send a video, etc.
So I really didn't expect this. Your rom is good, otherwise I probably wouldn't even test it. If you do not want the details to be resolved, then I will not use rom. I also interpret your comments on my YouTube technology channel.

I am no longer interested in participating in the development of your rom and reporting bugs. When you prefer some form of praising the Roma and do not totally address the problem as such. Good luck in life and other projects.

**Comment by truefriend-cz** [comment]
africabloe, you are one from developers?

**Comment by bimus** [comment]
@truefriend-cz allow me to butt in, seems like there's a communication breakdown! the rom is developed by zeelog, you are replying to another user who simply reported that he is not encountering such issues. You are addressing the wrong person I guess :-) peace.

**Comment by zeelog** [comment]
> Hello. Battery level issue. Every approx. 30 seconds, it turns off for about half a second and turns on the LED while charging the battery.
> 
> Edit:
> This úproblem have both versions Kernel 3.8 and 4.9.230, 4.9.231.

Re LED while charging - confirmed on 4.9, thanks - will check. Didn't notice issue on 3.18 though.

**Comment by zeelog** [comment]
should be fixed on latest build  https://github.com/zeelog/OTA/releases/tag/13.0
