### ISSUE TITLE
Crashing/freezing after installation

### ISSUE THREAD

**Issue by SucceedSucceed** [zeelog/OTA#10]
lineage-17.1-20200822-UNOFFICIAL-3.18-mido and lineage-17.1-20200901-UNOFFICIAL-4.9-mido are crashing/freezing and rebooting (only with 4.9 Kernel) after a few seconds after the LOS boot animation is complete.

The problem occurs with and without flashing gapps.

ROMs were flashed with twrp-3.3.1-3-KudProject-mido after latest MIUI global stable (mido_global_images_V11.0.2.0.NCFMIXM_20191107.0000.00_7.0_global).

it's hard to get any logs, as I cant authorize adb in that short time period.

**Comment by zeelog** [comment]
This is not a ROM issue, try clean wipe just in case you didn't + if previously encrypted, format. Perhaps you need to fix persist partition - sure you can find some guides somewhere.

**Comment by davidtrpcevski** [comment]
I think this is kinda serious issue and it is still an issue as something is breaking persist partition. It occurred to me right now on my builds. Haven't figured out whether it is the ROM or the TWRP but something is wrong, will check thoroughly. 

Here is another one, https://github.com/zeelog/OTA/issues/6
