### ISSUE TITLE
Zip Treble Compatibility Error

### ISSUE THREAD

**Issue by Psychoses** [zeelog/OTA#13]
Hi,

I need help, i use the last twrp-3.3.1-0-mido but when i update with the OTA zip, i got a "Zip Treble Compatibility Error".
Each time i need open the zip and remove compatibility.zip file inside for update with success.

Why i need to do that ? Someone can explain me the magic here ? This can be fixed ?

Thx

**Comment by thomasp-66** [comment]
Use Orangefox ( https://orangefox.download/en/device/mido ) or KudProject ( https://kudnet.id/downloads/twrp/mido/ ) recovery.

**Comment by Psychoses** [comment]
Thx for the tips @thomasp-66 i have switch from twrp to orangefox and all works like expected. I close the issue, thx again.
