### ISSUE TITLE
The proximity sensor does not work properly in stock dilaler app

### ISSUE THREAD

**Issue by baibradar75** [zeelog/OTA#14]
When called, the display goes out when you approach the ear. But when you move away from the ear or at the end of the call, the display does not activate. To activate, you must press the power button or touch the fingerprint sensor. This only happens on lineage-17.1-20200928-UNOFFICIAL-4.9-mido build. In lineage-17.1-20201008-UNOFFICIAL-3.18-mido the proximity sensor works correctly.

**Comment by zeelog** [comment]
should be fine on latest release 12th Oct.

**Comment by melifarrro** [comment]
does not work on the last release (and on the previous one too) when the call is quickly completed, but it works, but if it does not work a little longer, the screen does not turn on.
