### ISSUE TITLE
Any "official" oder recommended place for discussion on this rom?

### ISSUE THREAD

**Issue by momo42** [zeelog/OTA#16]
Hi zeelog, hi everyone,

I found this very nice rom by accident because someone directly linked to its files in this thread on XDA:

https://forum.xda-developers.com/redmi-note-4/xiaomi-redmi-note-4-snapdragon-roms-kernels-recoveries--other-development/unofficial-lineageos-17-1-t4039907

In my opinion, zeelog, you managed to create the most usable up to date rom for our beloved mido phones.
I searched the web but wasn't able to find a place for discussion other than this github issue tracker.
Now I wonder if you're hiding this rom on purpose, because you made it for yourself and don't want to drown in bug reports, or if I just haven't found the right place (forum, blog, messanger group, ...?) where discussion takes place.

I'd really like to have a spot for documentation and exchange with other users, but also know that this bug tracker here is actually not the right place for that. (maybe documentation but not discussion)

If there IS such a place, please point me there, if not, please consider starting a Thread on XDA or in some other android forum and give us a link!

Thanks for sharing your work with us! :-)

Regards
Momo

**Comment by anandsvm** [comment]
You can unofficial support group 
Lineage OS - RN4 -Zeelog
Unoffical Discussion group for Zeelog Mido Builds
https://t.me/LOSRN4
