### ISSUE TITLE
Data & obb folders are disappearing while copying files inside Android folder

### ISSUE THREAD

**Issue by africabloe** [zeelog/OTA#18]
Hello Zeelog,
I am using your roms since May. They are the most advanced roms among the others for our mido.
On the latest Lineage OS 18 R 4.9 I have two problems...
Clean Installation 
Wiped System, Data, Dalvik, Cache, Vendor, Internal Storage.
1. Screenshot partial or normal, does not work on Power Button . 
2. I cannot see other folders inside the Internal Storage/Android folder except "media" folder, when I am trying **to copy** files there. Otherwise I can see normally the contents of the Android folder (data, media, obb). See a small video here: https://streamable.com/bm4boi

Thank you very much for all your work!

**Comment by anandmd4** [comment]
1) Screenshot issue is fixed now in the latest update.
2) Its the latest restriction in Android 11. Use PC to access Android folger.

**Comment by africabloe** [comment]
Thank you for the answer!

I went back to 17.1 4.9 for a while. It is a very powerful system. Very stable, very fast, secure, light, smooth, ergonomic, with multitasking capabilities.

The apps are not stable yet on LOS 18.0. They need developing for Android R/11
Yes I know Zeelog is the Lord of our Mido. Of course he fixed screenshot issue and any other bug.

I do not like the new restrictions on Android R
https://developer.android.com/about/versions/11/privacy/storage#scoped-storage
