### ISSUE TITLE
An update didn't conserve Magisk Root

### ISSUE THREAD

**Issue by AkechiShiro** [zeelog/OTA#19]
I don't know if this is intended or not but an update (17.1-20201105-UNOFFICIAL-4.9-mido) removed my Magisk Root (the app was still installed on the phone but Magisk said that the RAMDISK wasn't modified). I had lost fingerprinting capabilities. Then I did reflash Magisk in the recovery and I saw that my fingerprint scan is working now, along with Root and all my Magisk modules were still installed meaning Magisk wasn't completely deleted by the OTA I suppose.

I'm under the Kernel 4.9, 17.1-20201105-UNOFFICIAL-4.9-mido, on a Redmi Note 4.

**Comment by amitzeo007** [comment]
During OTA update or Dirty Flash, The Boot partition is overwritten by the boot.img of the new OTA ROM. That is the reason the Modified Ramdisk is gone. But, the data partition remains unchanged, So, the app and modules remained.

**Comment by AkechiShiro** [comment]
Okay so this is an expected behavior and not something wrong I guess ? Then I'm sorry for having opened this issue. I had done OTA updates before but the modified ramdisk would be kept somehow, and I didn't have to reflash Magisk from the TWRP hence why I thought it wasn't the usual behavior (maybe some OTA from before didn't update the boot.img, but I think all of them do that, so I don't know what happened, maybe there is some sort of mechanism/feature which can preserve the modified ramdisk that failed for me).

**Comment by amitzeo007** [comment]
Yes. Removal of magisk after ota update is an expected behaviour. What happened before with you (root access remained) is unexpected.
