### ISSUE TITLE
Final 17.1 Q 4.9 & 3.18 are not stable

### ISSUE THREAD

**Issue by africabloe** [zeelog/OTA#22]
Hello Zeelog, I am using your roms since May. 
All of the releases all this time were perfect and stable. 
I used mostly the 4.9 roms + OpenGappsNano. 
Nevertheless, the final rom for 17.1 Q 4.9 is not stable. 
I used the stock kernel and my usual apps.
Anytime my phone is idle and I open it and I am starting an application, then it force close.
I have this problem sometimes even during the using of the mobile and it comes from nowhere.
2 or 3 times I had self-reboots.
So I decided to change to the final rom 17.1 Q 3.18.
I had the same problems.
All the previous roms from May till now they didn't had these errors.
Now I am using the previous of the final  17.1 Q 4.9 2020/11/05 with the stock boot.img of the final rom 17.1 Q 4.9 2020/12/15.
It works better than all the other roms and from 18.1 R 4.9 + NikGappsCore, which is not so good yet due to unprepared apps for Android 11 and issues of the Gapps.
Thank you very much for all your work dear master of mido!

**Comment by anandsvm** [comment]
You can't jump between LoS 17.1 to LoS 18.1 4.9. So clean flash to avoid any issues

**Comment by africabloe** [comment]
Sorry @anandsvm , but your answer has nothing to do with the problem I mentioned above
