### ISSUE TITLE
problem with the proximity sensor when making a call

### ISSUE THREAD

**Issue by melifarrro** [zeelog/OTA#25]
On all the latest builds of the 4.9 kernel (17.1 and 18.0) there is a problem with the proximity sensor when calling. The screen does not turn on. But if the phone is connected to a charger or adb is running, the sensor will work correctly.

**Comment by anandsvm** [comment]
Probably the agressive doze might be reason . Never experienced this issue though. Will test it.

**Comment by baibradar75** [comment]
There can be no agressive doze during a phone call.

**Comment by baibradar75** [comment]
In LOS-18.1-20210107 proximity sensor does not work correctly on phone calls. The screen does not turn on when calling end.
When the call is quickly completed, but it works, when the call lasts longer, the screen does not turn on.
No GAPPS instaled.

PLEASE FIX.

**Comment by melifarrro** [comment]
in last builds are correct work proximity sensors
