### ISSUE TITLE
gamepads usb do not work

### ISSUE THREAD

**Issue by mipocov** [zeelog/OTA#36]
Gamepads by usb otg do not work, the same gamepad connected bluetooth if it works well (it disconnects very often so I try to use it by usb). Tested xbox one and xbox 360 gamepads via usb otg which work on other roms and devices.

I read same issue in others roms with android 11  https://forums.oneplus.com/threads/otg-game-controller-not-working-even-when-otg-is-enabled-in-system-settings.1313130/

Thanks for the work you do with our devices :)

**Comment by zeelog** [comment]
confirmed working fine with this flashable kernel: https://mega.nz/file/4xMjxYAa#upSY8putGARFXkDMbP1zdkvdrLjvpt6HEdtHC24Hgzs

**Comment by mipocov** [comment]
thank you very much, I'm going to try it
