### ISSUE TITLE
Rotate icon

### ISSUE THREAD

**Issue by truefriend-cz** [zeelog/OTA#38]
Please dev disable Rotate sugestion icon.... (left bottom if locked rotation but rotate phone)...
solution is maybe this:
`adb shell settings put secure show_rotation_suggestions 0`
Thanks

**Comment by gui616** [comment]
Please, don't disable rotation suggestion. I like it.
Maybe you could create menu to enable and disable in configuration app.

**Comment by melifarrro** [comment]
Yes, I agree, you do not need to turn it off, I also like this function of manually switching the screen rotation.

**Comment by truefriend-cz** [comment]
You can turn on this feature in a total of four places in the settings. Two of them are: 1. v Display settings, 2. v Quick View. I don't understand why someone else needs to activate this function in the fifth place directly on the display where it already covers part of the content.
So I am inclined not to deactivate but to switch it off.

**Comment by melifarrro** [comment]
> You can turn on this feature in a total of four places in the settings. Two of the best available are: 1. v Display Settings, 2. v Quick View. I don't understand why someone else needs to activate this function in the fifth place directly on the display where it already covers part of the content. You can also add an icon for adjusting the brightness and volume.
> And if someone already requires it, it would probably be nice for this icon to be displayed to deactivate this function (it will remain on the screen even if the rotation is turned on).
> I am inclined to ensure that this proposal is not deactivated but can be switched off with a switch.

what's stopping you from this disappearing display rotation icon? it disappears after a couple of seconds

**Comment by truefriend-cz** [comment]
Please add switch item for disable/enable for this.
