### ISSUE TITLE
Hotspot Issues.

### ISSUE THREAD

**Issue by Sunny-Prabhat** [zeelog/OTA#41]
So here's the problem.
The Hotspot turns on without any issue, but when we try to connect to that Hotspot in other device, it connects without any problem, but afterwards the phone(Mido), automatically switches off and restarts.
This shit is happening every single time.
Please fix it in the next update.
I'm going to downgrade the os version.
Btw thanks for an awesome software, I find this os very clean and light weight with great performance.

**Comment by ri5h46h** [comment]
hello, @Sunny-Prabhat another separate kernel image has been already released to fix this issue. You can flash that kernel and use it if you wish to or wait for the next update
