### ISSUE TITLE
No sms app working  to send sms

### ISSUE THREAD

**Issue by Avhay** [zeelog/OTA#44]
![Screenshot_20210720-103340_Messaging](https://user-images.githubusercontent.com/87666664/126264765-5d39d072-f0cf-4a5b-9637-2b08e68ba7e3.png)
![Screenshot_20210720-103326_Messages](https://user-images.githubusercontent.com/87666664/126264770-7880a058-c65d-4127-9a03-566e44bd5eac.png)

**Comment by ri5h46h** [comment]
can you please tell if it shows you any error code when it fails to send an sms?
