### ISSUE TITLE
Phone reboots when trying to use wireless display

### ISSUE THREAD

**Issue by kyak** [zeelog/OTA#45]
Hi,

Using the latest OTA package here, nothing on top of it (no root, no magisk, no google services).

When trying to mirror phone to TV (miracast, I guess), I can see my TV in the list. When trying to connect to TV, phone just hangs for a couple of seconds and then reboots.

**Comment by Roker2** [comment]
Send please logs.

Your steps:
1) start getting log via ADB (connect device to PC via USB)
adb logcat > log.txt
And don't unconnect device
2) try to connect to TV via Miracast
3) getting logs will be stopped with device rebooting
4) save logs to dogbin, gist or pastebin

**Comment by kyak** [comment]
Attached is the logcat

[log.txt](https://github.com/zeelog/OTA/files/6873749/log.txt)

I've captured the log since the moment I press on the TV's name.

**Comment by intika** [comment]
Bug confirmed... this was introduced by the last build's Kernel, if we flash the kernel of the previous build (18.1-20210610) the bug does not occur...   I did not get significant information on the logcat...

**Comment by kyak** [comment]
Fixed in August update. Thanks guys!
