### ISSUE TITLE
Unable to turn on Wi-Fi and Bluetooth

### ISSUE THREAD

**Issue by Talmio216** [zeelog/OTA#65]
Sought to upgrade from the stock firmware. Successfully flashed the 18.1 release using the latest TWRP, with the default wipe options (dalvik, cache and data). No error appeared during the installation. However, after booting into the system, the SIM card wasn't detected, and both Wi-Fi and Bluetooth modules were turned off. Clicking on Wi-Fi and Bluetooth icons does nothing, except for a mild device hang (and sometimes a message saying the UI is not responding).

After reflashing and upgrading to 19.1, the error persisted. It also persisted in any other ROM. It seems, the only way to repair the modules is to flash the stock ROM with Android 7 / MIUI 11. 

I hope the `dmesg` output would be helpful:
[dmesg-log.txt](https://github.com/zeelog/OTA/files/8763474/dmesg-log.txt)

**Comment by zeelog** [comment]
most probably caused by incompatible gapps variant.
report any issues on telegram group: https://t.me/LOSRN4
