### ISSUE TITLE
Troubles in some apps, which use fingerprint

### ISSUE THREAD

**Issue by Roker2** [zeelog/OTA#66]
Hi! Some users said, that they has errors with fingerprint in some apps. But they said, that no problems with same apps in PE.
DT commit: https://github.com/PixelExperience-Devices/device_xiaomi_mido/commit/523f2191e14bae2038eb89dd75cab824db672d60
FWB commit: https://github.com/PixelExperience/frameworks_base/commit/76da12071174ad80fd4f59929142ab708439ceaf

**Comment by zeelog** [comment]
Thanks! will check it out
