### ISSUE TITLE
Enable WiFi WPA3

### ISSUE THREAD

**Issue by DrHurt** [zeelog/OTA#75]
With most new routers now supporting WPA3, I would like to request that you enable WPA3 on mido as it’s more efficient (at encrypting data) and faster (to connect to).

I believe native support has been added to android 10 so it shouldn’t be too big of a job.

Thank you 

https://source.android.com/docs/core/connect/wifi-wpa3-owe

**Comment by zeelog** [comment]
unfortunately wpa3 is not supported on mido (& on many older devices)
