### ISSUE TITLE
OpenSteeetMap can't find my location

### ISSUE THREAD

**Issue by Vitalya-code** [zeelog/OTA#79]
OpenSteeetMap can't find my location even if i grant access and enable GPS
Also i tryed other apps like OsmAnd or StreetComplete and it is still not working

![Screenshot_20221103-200001_Trebuchet.png](https://user-images.githubusercontent.com/58048618/199799477-55cba192-dc2d-450b-a9a0-81984ba40da3.png)

**Comment by Roker2** [comment]
As I know, Qualcomm broke GPS for some Europe countries.

**Comment by Vitalya-code** [comment]
Maybe it's phone problem
