### ISSUE TITLE
Vioce Input options not available under Languages & Input (Speech)

### ISSUE THREAD

**Issue by pranjalisnow** [zeelog/OTA#82]
Hi,

Just thought I will update regarding an option I was missing on the latest LineageOS 20 (24-12-2022 version).
There is no way to add **Speech** languages in the settings.

Please see if this option can be added.
Or, if this is already present, how does one add voices for speech?

(screenshots below)

![Screenshot_20221230-133141_Settings](https://user-images.githubusercontent.com/52067888/210048767-d11d8871-56a4-4590-a6b2-b7decc1c3130.png)

![Screenshot_20221230-133144_Settings](https://user-images.githubusercontent.com/52067888/210048593-81a5b3e2-b030-422f-b98d-83d92479157a.png)

**Comment by Roker2** [comment]
Maybe it required any additional component by Google?

**Comment by zeelog** [comment]
try installing speech services by google:

![image](https://user-images.githubusercontent.com/2109514/210097810-94520624-82f8-45e1-a631-5c2098432edc.png)

**Comment by pranjalisnow** [comment]
> try installing speech services by google:
> 
> ![image](https://user-images.githubusercontent.com/2109514/210097810-94520624-82f8-45e1-a631-5c2098432edc.png)


Will try this option and revert.
Thank you.

**Comment by pranjalisnow** [comment]
It's working now after installing the Speech services.
Thank you.
